server:
  port: 8888

spring:
  application:
    name: hikari-connection-pool-metrics
  datasource:
    oracle-db:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: test
      password: test
      pool-name: oracle-pool
      maximum-pool-size: 20
      data-source-properties:
        oracle.jdbc.implicitStatementCacheSize: 100
    mysql-db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      pool-name: mysql-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
    h2-db:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      pool-name: h2-pool
      maximum-pool-size: 5

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

logging:
  level:
    com.zaxxer.hikari: DEBUG